// Zodiac constants
export const ZODIAC_VALUES: Record<string, number> = {
  Tý: 1,
  Sửu: 2,
  Dần: 3,
  Mão: 4,
  Thìn: 5,
  Tỵ: 6,
  Ngọ: 7,
  Mùi: 8,
  Thân: 9,
  Dậu: 10,
  Tuất: 11,
  Hợi: 12,
}

export const ZODIAC_HOURS = [
  { label: "Tý (23:00-01:00)", value: 1 },
  { label: "Sửu (01:00-03:00)", value: 2 },
  { label: "Dần (03:00-05:00)", value: 3 },
  { label: "Mão (05:00-07:00)", value: 4 },
  { label: "Thìn (07:00-09:00)", value: 5 },
  { label: "Tỵ (09:00-11:00)", value: 6 },
  { label: "Ngọ (11:00-13:00)", value: 7 },
  { label: "Mùi (13:00-15:00)", value: 8 },
  { label: "Thân (15:00-17:00)", value: 9 },
  { label: "Dậu (17:00-19:00)", value: 10 },
  { label: "Tuất (19:00-21:00)", value: 11 },
  { label: "Hợi (21:00-23:00)", value: 12 },
]

// Trigram data with correct lines representation
export { PLUM_BLOSSOM_TRIGRAMS as TRIGRAMS } from "./data/plum-blossom-data"
export { EARTHLY_BRANCHES } from "./data/plum-blossom-data"

// Hexagram names (64 hexagrams)
export const HEXAGRAM_NAMES: Record<string, string> = {
  "1-1": "乾為天 (Càn Vi Thiên)",
  "1-2": "天澤履 (Thiên Trạch Lý)",
  "1-3": "天火同人 (Thiên Hỏa Đồng Nhân)",
  "1-4": "天雷無妄 (Thiên Lôi Vô Vọng)",
  "1-5": "天風姤 (Thiên Phong Cấu)",
  "1-6": "天水訟 (Thiên Thủy Tụng)",
  "1-7": "天山遯 (Thiên Sơn Độn)",
  "1-8": "天地否 (Thiên Địa Phủ)",
  "2-1": "澤天夬 (Trạch Thiên Quải)",
  "2-2": "兌為澤 (Đoài Vi Trạch)",
  "2-3": "澤火革 (Trạch Hỏa Cách)",
  "2-4": "澤雷隨 (Trạch Lôi Tùy)",
  "2-5": "澤風大過 (Trạch Phong Đại Quá)",
  "2-6": "澤水困 (Trạch Thủy Khốn)",
  "2-7": "澤山咸 (Trạch Sơn Hàm)",
  "2-8": "澤地萃 (Trạch Địa Tụy)",
  "3-1": "火天大有 (Hỏa Thiên Đại Hữu)",
  "3-2": "火澤睽 (Hỏa Trạch Khuy)",
  "3-3": "離為火 (Ly Vi Hỏa)",
  "3-4": "火雷噬嗑 (Hỏa Lôi Thệ Hạp)",
  "3-5": "火風鼎 (Hỏa Phong Đỉnh)",
  "3-6": "火水未濟 (Hỏa Thủy Vị Tế)",
  "3-7": "火山旅 (Hỏa Sơn Lữ)",
  "3-8": "火地晉 (Hỏa Địa Tấn)",
  "4-1": "雷天大壯 (Lôi Thiên Đại Tráng)",
  "4-2": "雷澤歸妹 (Lôi Trạch Quy Muội)",
  "4-3": "雷火豐 (Lôi Hỏa Phong)",
  "4-4": "震為雷 (Chấn Vi Lôi)",
  "4-5": "雷風恆 (Lôi Phong Hằng)",
  "4-6": "雷水解 (Lôi Thủy Giải)",
  "4-7": "雷山小過 (Lôi Sơn Tiểu Quá)",
  "4-8": "雷地豫 (Lôi Địa Dự)",
  "5-1": "風天小畜 (Phong Thiên Tiểu Súc)",
  "5-2": "風澤中孚 (Phong Trạch Trung Phu)",
  "5-3": "風火家人 (Phong Hỏa Gia Nhân)",
  "5-4": "風雷益 (Phong Lôi Ích)",
  "5-5": "巽為風 (Tốn Vi Phong)",
  "5-6": "風水渙 (Phong Thủy Hoán)",
  "5-7": "風山漸 (Phong Sơn Tiệm)",
  "5-8": "風地觀 (Phong Địa Quan)",
  "6-1": "水天需 (Thủy Thiên Nhu)",
  "6-2": "水澤節 (Thủy Trạch Tiết)",
  "6-3": "水火既濟 (Thủy Hỏa Ký Tế)",
  "6-4": "水雷屯 (Thủy Lôi Truân)",
  "6-5": "水風井 (Thủy Phong Tỉnh)",
  "6-6": "坎為水 (Khảm Vi Thủy)",
  "6-7": "水山蹇 (Thủy Sơn Kiển)",
  "6-8": "水地比 (Thủy Địa Tỷ)",
  "7-1": "山天大畜 (Sơn Thiên Đại Súc)",
  "7-2": "山澤損 (Sơn Trạch Tổn)",
  "7-3": "山火賁 (Sơn Hỏa Bí)",
  "7-4": "山雷頤 (Sơn Lôi Di)",
  "7-5": "山風蠱 (Sơn Phong Cổ)",
  "7-6": "山水蒙 (Sơn Thủy Mông)",
  "7-7": "艮為山 (Cấn Vi Sơn)",
  "7-8": "山地剝 (Sơn Địa Bác)",
  "8-1": "地天泰 (Địa Thiên Thái)",
  "8-2": "地澤臨 (Địa Trạch Lâm)",
  "8-3": "地火明夷 (Địa Hỏa Minh Di)",
  "8-4": "地雷復 (Địa Lôi Phục)",
  "8-5": "地風升 (Địa Phong Thăng)",
  "8-6": "地水師 (Địa Thủy Sư)",
  "8-7": "地山謙 (Địa Sơn Khiêm)",
  "8-8": "坤為地 (Khôn Vi Địa)",
}
